spring:
  application:
    name: product-service
#  config:
#    import: optional:configserver:http://localhost:8888/
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: configserver

---
spring:
  config:
    activate:
      on-profile: local
    import: optional:configserver:http://localhost:8888/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.netflix.eureka: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.cloud: INFO
