server:
  port: 8888

spring:
  application:
    name: configserver

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        native:
          search-locations: file:${user.dir}/config-server/config

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
